M48
; DRILL file KiCad 10.0.3 date 2026-08-09T22:28:27
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-09T22:28:27-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.991
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.250
%
G90
G05
T1
X75.38Y-105.734
X83.0Y-104.718
X83.0Y-106.75
T2
X52.5Y-102.35
X52.5Y-113.78
M30
